-- AlterTable
ALTER TABLE "users" ADD COLUMN     "ctr" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "linksCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalClicks" INTEGER NOT NULL DEFAULT 0;
